In [1]:
# virtualbox
# matf-artificial-intelligence
# user - student
# terminal - jupyter notebook
# https://github.com/MATF-istrazivanje-podataka-1/live
# 06

In [2]:
import pandas as pd

In [6]:
df = pd.read_csv('../balloons.csv')

In [19]:
df

color   size      act    age inflated
0   YELLOW  SMALL  STRETCH  ADULT        T
1   YELLOW  SMALL  STRETCH  ADULT        T
2   YELLOW  SMALL  STRETCH  CHILD        F
3   YELLOW  SMALL      DIP  ADULT        F
4   YELLOW  SMALL      DIP  CHILD        F
..     ...    ...      ...    ...      ...
71  PURPLE  SMALL      DIP  CHILD        F
72  PURPLE  LARGE  STRETCH  ADULT        F
73  PURPLE  LARGE  STRETCH  CHILD        F
74  PURPLE  LARGE      DIP  ADULT        F
75  PURPLE  LARGE      DIP  CHILD        F

[76 rows x 5 columns]

In [20]:
df.describe()

color   size      act    age inflated
count       76     76       76     76       76
unique       2      2        2      2        2
top     YELLOW  SMALL  STRETCH  CHILD        F
freq        40     40       38     38       41

In [9]:
X = df.drop('inflated', axis=1)
X.shape

(76, 4)

In [10]:
y = df['inflated']
y.shape

(76,)

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=313, stratify=y)

In [13]:
X_train.shape

(60, 4)

In [21]:
X_test.shape

(16, 4)

In [22]:
from sklearn.preprocessing import OrdinalEncoder

In [23]:
oe = OrdinalEncoder()

In [24]:
oe.fit(X_train)

OrdinalEncoder(categories='auto', dtype=<class 'numpy.float64'>)

In [25]:
oe.categories_

[array(['PURPLE', 'YELLOW'], dtype=object),
 array(['LARGE', 'SMALL'], dtype=object),
 array(['DIP', 'STRETCH'], dtype=object),
 array(['ADULT', 'CHILD'], dtype=object)]

In [27]:
X_train = oe.transform(X_train)

In [29]:
X_test = oe.transform(X_test)

In [15]:
from sklearn.naive_bayes import CategoricalNB

In [30]:
model = CategoricalNB()

In [31]:
model.fit(X_train, y_train)

CategoricalNB(alpha=1.0, class_prior=None, fit_prior=True)

In [32]:
model.category_count_

[array([[17., 15.],
        [11., 17.]]),
 array([[19., 13.],
        [10., 18.]]),
 array([[23.,  9.],
        [ 7., 21.]]),
 array([[12., 20.],
        [20.,  8.]])]

In [33]:
model.class_count_

array([32., 28.])

In [34]:
y_pred = model.predict(X_test)

In [35]:
from sklearn.metrics import confusion_matrix

In [36]:
confusion_matrix(y_test, y_pred)

array([[7, 2],
       [1, 6]])

In [44]:
corpus = ['Chinese Chinese Beijing',
         'Chinese Chinese Shanghai',
         'Chinese Macau',
         'Chinese Tokyo Japan',]

In [45]:
classes = ['yes', 'yes', 'yes', 'no']

In [66]:
X_test = ['Chinese Tokyo Japan CHinese chinese']

In [47]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.feature_extraction import DictVectorizer

In [48]:
vectorizer = CountVectorizer()

In [49]:
vectorizer.fit(corpus)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [50]:
vectorizer.get_feature_names()

['beijing', 'chinese', 'japan', 'macau', 'shanghai', 'tokyo']

In [52]:
X_train = vectorizer.transform(corpus)

In [54]:
X_train.toarray()

array([[1, 2, 0, 0, 0, 0],
       [0, 2, 0, 0, 1, 0],
       [0, 1, 0, 1, 0, 0],
       [0, 1, 1, 0, 0, 1]])

In [55]:
X_train = pd.DataFrame(X_train.toarray(), columns=vectorizer.get_feature_names())
X_train

beijing  chinese  japan  macau  shanghai  tokyo
0        1        2      0      0         0      0
1        0        2      0      0         1      0
2        0        1      0      1         0      0
3        0        1      1      0         0      1

In [56]:
from sklearn.naive_bayes import MultinomialNB

In [59]:
model = MultinomialNB()

In [68]:
y_train = classes

In [69]:
X_train

beijing  chinese  japan  macau  shanghai  tokyo
0        1        2      0      0         0      0
1        0        2      0      0         1      0
2        0        1      0      1         0      0
3        0        1      1      0         0      1

In [61]:
model.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [62]:
model.class_count_

array([1., 3.])

In [64]:
model.feature_count_

array([[0., 1., 1., 0., 0., 1.],
       [1., 5., 0., 1., 1., 0.]])

In [71]:
X_test = vectorizer.transform(X_test)

In [73]:
X_test.toarray()

array([[0, 3, 1, 0, 0, 1]])

In [74]:
model.predict(X_test)

array(['yes'], dtype='<U3')

In [2]:
import os

In [86]:
def read_data(root_dir):
    corpus = []
    classes = []
    for class_name in os.listdir(root_dir):
        dir_path = os.path.join(root_dir, class_name)
        for file_name in os.listdir(dir_path):
            file_path = os.path.join(dir_path, file_name)
            word_counts = {}
            with open(file_path, 'r') as f:
                for line in f:
                    word, count = line.split()
                    word_counts[word] = int(count)
            corpus.append(word_counts)
            classes.append(class_name)
    return corpus, classes

In [87]:
X_train, y_train = read_data('../ebart/ebart/VektoriEbart-5/Skup/')

In [88]:
len(X_train)

3492

In [89]:
len(y_train)

3492

In [90]:
from sklearn.feature_extraction import DictVectorizer

In [91]:
vectorizer = DictVectorizer()

In [92]:
vectorizer.fit(X_train)

DictVectorizer(dtype=<class 'numpy.float64'>, separator='=', sort=True,
               sparse=True)

In [93]:
X_train = vectorizer.transform(X_train)

In [94]:
len(vectorizer.feature_names_)

36830

In [95]:
3492*36830

128610360

In [96]:
import pandas as pd

In [97]:
X_train = pd.DataFrame(X_train.toarray(), columns=vectorizer.feature_names_)

In [98]:
X_train.iloc[1281, :]

ab             0.0
abasu          0.0
abati          0.0
abc            0.0
abdul          0.0
              ... 
zxutih         0.0
zxutilovine    0.0
zxuto          0.0
zxutra         0.0
zxuzxa         0.0
Name: 1281, Length: 36830, dtype: float64

In [99]:
from sklearn.naive_bayes import MultinomialNB

In [100]:
model = MultinomialNB()

In [101]:
model.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [102]:
y_train_pred = model.predict(X_train)

In [103]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [104]:
accuracy_score(y_train, y_train_pred)

0.9401489117983963

In [105]:
confusion_matrix(y_train, y_train_pred)

array([[312,   4,   3,  14,   0],
       [ 13, 504,   5,  97,   1],
       [  1,   4, 614,   6,   2],
       [  9,  28,   6, 885,   7],
       [  1,   4,   1,   3, 968]])

In [106]:
X_test, y_test = read_data('../ebart/ebart/VektoriEbart-5/Testing/')

In [107]:
len(X_test)

1743

In [108]:
len(y_test)

1743

In [109]:
X_test = vectorizer.transform(X_test)

In [110]:
y_test_pred = model.predict(X_test)

In [111]:
accuracy_score(y_test, y_test_pred)

0.8995983935742972

In [112]:
confusion_matrix(y_test, y_test_pred)

array([[152,   0,   1,  13,   0],
       [ 10, 226,   6,  66,   1],
       [  2,   0, 301,   6,   4],
       [  8,  36,   9, 411,   3],
       [  2,   1,   1,   6, 478]])

In [113]:
X_test = X_test.toarray()

In [114]:
from sklearn.neighbors import KNeighborsClassifier

In [115]:
model = KNeighborsClassifier()

In [116]:
model.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [117]:
y_pred = model.predict(X_test)

In [118]:
accuracy_score(y_test, y_pred)

0.6047045324153758

In [119]:
from sklearnearnearn.tree import DecisionTreeClassifier

/home/stefan/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [120]:
model = DecisionTreeClassifier()

In [121]:
model.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [122]:
y_pred = model.predict(X_test)

In [123]:
accuracy_score(y_test, y_pred)

0.74469305794607

In [124]:
from sklearn.neural_network import MLPClassifier

In [133]:
model = MLPClassifier(hidden_layer_sizes=(100,80,60), max_iter=10)

In [134]:
model.fit(X_train, y_train)

/home/stefan/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(100, 80, 60), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=10,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [135]:
y_train_pred = model.predict(X_train)

In [136]:
accuracy_score(y_train, y_train_pred)

1.0

In [137]:
y_pred = model.predict(X_test)

In [138]:
accuracy_score(y_test, y_pred)

0.8881239242685026